baseURL = 'example.org/'
languageCode = 'en-us'
title = 'Hugo & Fermyon Spin Template'
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Sample site to showcase Hugo sites being served by Fermyon Spin"
  copyright = "Copyright © 2023 Thorsten Hans"
  dark = "off"
  highlight = true
